version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./.docker/backend/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./backend
        target: /api
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - default

  frontend:
    build:
      context: .
      dockerfile: ./.docker/frontend/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    ports:
      - "3333:3333"

networks:
  default:
volumes:
  postgres: