version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./.docker/backend/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./backend
        target: /api
    depends_on:
      - postgres
    networks:
      - api
    ports:
      - '3000:3000'

  postgres:
    container_name: postgres
    restart: always
    image: postgres:13
    ports:
      - '5432:5432'
    networks:
      - api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      TZ: 'Asia/Tokyo'
    volumes:
      - postgres:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./.docker/frontend/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    ports:
      - '3333:3333'

networks:
  api:
    driver: bridge

volumes:
  postgres:
