@startuml
'https://plantuml.com/ja/use-case-diagram

title ユースケース
header created by jp-knj

left to right direction
actor "参加者" as Actor
rectangle 集団タスク管理アプリ {
  usecase "ログイン" as AuthenticationUC1
  Actor --> AuthenticationUC1

  usecase "全ての参加者を一覧する" as AllUsersUC1
  Actor --> AllUsersUC1

  usecase "全てのタスクを一覧する" as TaskUC1
  Actor --> TaskUC1

  usecase "タスクのステータスを更新する" as TaskUC2
  Actor --> TaskUC2

  usecase "参加者自身のステータスを更新する" as MemberUC1
  Actor --> MemberUC1

  usecase "別のペアへ移動する" as PairUC1
  Actor --> PairUC1

  usecase "他のチームへ移動する" as TeamUC1
  Actor --> TeamUC1
}
@enduml