@startuml
'https://plantuml.com/ja/use-case-diagram

title ユースケース
header created by jp-knj

left to right direction
actor "参加者" as Actor
rectangle 集団タスク管理アプリ {
  usecase "ログイン" as AuthenticationUC1
  Actor --> AuthenticationUC1

  rectangle 参加者 {
    usecase "全ての参加者を一覧する" as MemberGetAllUseCase
    Actor --> MemberGetAllUseCase

    usecase "メールアドレスを変更する" as MemberUpdateEmailUseCase
    Actor --> MemberUpdateEmailUseCase
  }

  rectangle 課題 {
    usecase "全ての担当した課題を一覧する" as TaskGetAllUseCase
    Actor --> TaskGetAllUseCase

    usecase "担当した課題の進捗ステータスを変更する" as TaskUpdateStatusUseCase
    Actor --> TaskUpdateStatusUseCase
  }

  usecase "タスクのステータスを更新する" as TaskUC2
  Actor --> TaskUC2

  usecase "参加者自身のステータスを更新する" as MemberUC1
  Actor --> MemberUC1

  usecase "別のペアへ移動する" as PairUC1
  Actor --> PairUC1

  usecase "他のチームへ移動する" as TeamUC1
  Actor --> TeamUC1
}
@enduml